import React from 'react';
import { Printer, Download, Share2, Shield, CheckCircle2, AlertTriangle, BookOpen, Compass } from 'lucide-react';
import { Property, VaastuAnalysisReport, Finding } from '../../types';

interface ReportViewProps {
  property: Property;
  report: VaastuAnalysisReport;
}

export const ReportView: React.FC<ReportViewProps> = ({ property, report }) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-16">
      {/* Top Action Ribbon */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3 bg-white p-4 rounded-2xl border border-stone-200 shadow-2xs print:hidden">
        <div>
          <h2 className="text-sm font-bold text-stone-900 font-serif">
            Comprehensive Vaastu Shastra Audit Report
          </h2>
          <p className="text-xs text-stone-500">
            Generated by VAASU AI COACH • Validated against Classical Treatises
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handlePrint}
            className="px-4 py-2 rounded-xl bg-amber-600 hover:bg-amber-500 text-white text-xs font-semibold flex items-center gap-1.5 shadow-xs transition-colors"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / Save as PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document */}
      <div className="bg-white rounded-2xl border border-stone-200 p-8 sm:p-12 shadow-sm space-y-8 print:p-0 print:border-none print:shadow-none text-stone-900 font-sans">
        {/* Document Header */}
        <div className="border-b-2 border-stone-900 pb-6 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-amber-700">
              <span>🏛️ VAASU AI COACH</span>
              <span>•</span>
              <span>ARCHITECTURAL AUDIT</span>
            </div>
            <h1 className="text-3xl font-extrabold font-serif text-stone-900 tracking-tight mt-1">
              {property.name}
            </h1>
            <p className="text-xs text-stone-500 mt-1">
              Location: {property.city}, {property.country} • Architectural Type: {property.propertyType}
            </p>
          </div>

          <div className="text-left sm:text-right space-y-1">
            <div className="text-xs font-mono text-stone-400">
              Audit Date: {new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}
            </div>
            <div className="text-xs font-semibold text-stone-700">
              True North: {property.northRotation}° • Facing: {property.facingDirection}
            </div>
          </div>
        </div>

        {/* Executive Summary & Overall Score Card */}
        <div className="p-6 rounded-2xl bg-stone-50 border border-stone-200 flex flex-col sm:flex-row items-center justify-between gap-6">
          <div className="space-y-2">
            <span className="text-xs font-bold uppercase tracking-wider text-amber-800">
              Executive Evaluation
            </span>
            <div className="text-2xl font-bold font-serif text-stone-900">
              {report.alignmentRating} ({report.overallScore}/100)
            </div>
            <p className="text-xs text-stone-600 max-w-xl leading-relaxed">
              Based on Mayamata, Brihat Samhita, and Samarangana Sutradhara tenets, this property demonstrates strong structural zoning with {report.positiveCount} positive placements. Targeted non-structural remedies are recommended for {report.reviewCount} areas to balance fire and water elements.
            </p>
          </div>

          <div className="w-28 h-28 rounded-2xl bg-white border-2 border-amber-600 flex flex-col items-center justify-center shadow-xs flex-shrink-0">
            <span className="text-3xl font-extrabold font-mono text-stone-900">
              {report.overallScore}
            </span>
            <span className="text-[10px] uppercase font-bold text-stone-400">Score / 100</span>
          </div>
        </div>

        {/* 9-Category Score Breakdown Table */}
        <div className="space-y-3">
          <h2 className="text-lg font-bold font-serif text-stone-900 border-b border-stone-200 pb-2">
            1. Comprehensive 9-Category Weighted Evaluation
          </h2>

          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left">
              <thead className="bg-stone-100 text-stone-700 uppercase font-semibold">
                <tr>
                  <th className="p-3">Category</th>
                  <th className="p-3 text-right">Total Points</th>
                  <th className="p-3 text-right">Score Earned</th>
                  <th className="p-3">Observations & Canonical Notes</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-200">
                {report.categoryScores.map((cat, i) => (
                  <tr key={i} className="hover:bg-stone-50/50">
                    <td className="p-3 font-semibold text-stone-900">{cat.category}</td>
                    <td className="p-3 text-right font-mono text-stone-500">{cat.totalPoints}</td>
                    <td className="p-3 text-right font-mono font-bold text-amber-900">
                      {cat.earnedPoints}
                    </td>
                    <td className="p-3 text-stone-600">{cat.notes}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Detailed Findings & Tiered Remedies Table */}
        <div className="space-y-3">
          <h2 className="text-lg font-bold font-serif text-stone-900 border-b border-stone-200 pb-2">
            2. Detailed Architectural Findings & Actionable Remedies
          </h2>

          <div className="space-y-4">
            {report.findings.map((f, i) => {
              const isPositive = f.severity === 'EXCELLENT' || f.severity === 'FAVORABLE';
              return (
                <div
                  key={f.id}
                  className="p-4 rounded-xl border border-stone-200 bg-white space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      {isPositive ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                      ) : (
                        <AlertTriangle className="w-4 h-4 text-amber-600" />
                      )}
                      <h4 className="text-sm font-bold text-stone-900">{f.title}</h4>
                    </div>
                    <span className="font-mono text-xs font-bold px-2 py-0.5 rounded bg-stone-100 text-stone-800">
                      Zone: {f.directionZone}
                    </span>
                  </div>

                  <p className="text-xs text-stone-600 leading-relaxed">{f.description}</p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1 text-xs">
                    {(f.recommendations?.level1Architectural || (f.recommendations as any)?.level1Structural) && (
                      <div className="p-2.5 rounded-lg bg-rose-50/60 border border-rose-200">
                        <span className="font-semibold text-rose-900">Level 1 (Structural / Layout):</span>{' '}
                        <span className="text-stone-700">
                          {f.recommendations?.level1Architectural || (f.recommendations as any)?.level1Structural}
                        </span>
                      </div>
                    )}
                    {f.recommendations?.level2Interior && (
                      <div className="p-2.5 rounded-lg bg-stone-50 border border-stone-200">
                        <span className="font-semibold text-stone-800">Level 2 (Interior Alignment):</span>{' '}
                        <span className="text-stone-600">{f.recommendations.level2Interior}</span>
                      </div>
                    )}
                    {(f.recommendations?.level3NonStructural || (f.recommendations as any)?.level3Remedy) && (
                      <div className="p-2.5 rounded-lg bg-amber-50/60 border border-amber-200">
                        <span className="font-semibold text-amber-900">Level 3 (Non-Structural):</span>{' '}
                        <span className="text-stone-700">
                          {f.recommendations?.level3NonStructural || (f.recommendations as any)?.level3Remedy}
                        </span>
                      </div>
                    )}
                  </div>

                  <div className="text-[10px] text-stone-400 pt-1">
                    Canonical Source: {f.sourceText || 'Traditional Sthapatya Veda'}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Disclaimer Footer */}
        <div className="border-t-2 border-stone-200 pt-6 text-[11px] text-stone-500 space-y-1.5 leading-relaxed">
          <div className="font-bold uppercase text-stone-700">
            Professional & Ethical Architectural Disclaimer
          </div>
          <p>
            VAASU AI COACH is an advisory, research, and educational platform bridging ancient Sthapatya Shastra with contemporary architectural design principles. All analyses are mathematical evaluations based on user-provided plans and classical texts. This report does not replace certified structural engineering, municipal building codes, or on-site architectural audits.
          </p>
          <div className="pt-2 text-stone-400">
            System: VAASU AI COACH v1.0 • Platform Architect: Pawan Paji • Certified Source Engine
          </div>
        </div>
      </div>
    </div>
  );
};
